rvm: 1.9.3
language: objective-c
before_script:
  - export LANG=en_US.UTF-8
  - gem install xcpretty
script: xcodebuild -workspace YapModel.xcworkspace -scheme YapModel -sdk iphonesimulator test | xcpretty -c; exit ${PIPESTATUS[0]}